### ISSUE TITLE
Render with the mermaid library instead of a remote server

### ISSUE THREAD

**Issue by KevinRizzoTO** [hkgnp/logseq-mermaid-plugin#9]
Mermaid can be run as a JavaScript library which, in my head, seems preferable to sending data over to a remote server. Was there a particular reason it was implemented this way?

**Comment by hkgnp** [comment]
Unfortunately, mermaid needs a browser to run, instead of just a nodejs environment. Hence the only way to get it locally in Logseq is to incorporate something like puppeteer, something which takes a little longer! I don't really use a mermaid myself regularly, so if you would like to have a go, please do! 

I certainly don't mind archiving this repo once that option is available,.

**Comment by KevinRizzoTO** [comment]
An FYI, a co-worker just found [this](https://github.com/xyhp915/logseq-fenced-code-plus/blob/main/src/mermaid.tsx) which suggests there might be some apis under `logseq.Experiments` that could be used to run code in the browser process (see [here](https://github.com/xyhp915/logseq-fenced-code-plus/blob/main/src/mermaid.tsx#L8) and [here](https://github.com/xyhp915/logseq-fenced-code-plus/blob/main/src/mermaid.tsx#L16-L22)). I'm not sure if this API is documented anywhere so might be a "use at your own risk" type of situation

**Comment by hkgnp** [comment]
Yeah looks good! The repo author is the Logseq guy in charge of APIs so I think it will be a much better plugin once it is available!

Have you tested it yet?

**Comment by KevinRizzoTO** [comment]
I personally didn't, but know that a few people at work have tried it and it seems to work okay for them

**Comment by hkgnp** [comment]
Will close this issue since there is an alternative available then!

**Comment by duaneking** [comment]
This should be reopened as its a critical security issue that actively violates security compliance.
